user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzQ4Mzc=
#vk1.a.knWxyyvripXjGTUjbP7c5bJnI0-RMwp4DCVpKIzj3-awCrcMQWVdFePVwawBVOR1PlvHgNO4Yq1ogepcjOkVQYrzqEY4PAmPE9neRwPlS0cR16MynB8W1CgHk54g6NSimNQicwNQc4RW9eh_HiI4WoThzLAkfyDdAclAF3P06qM7MITtdW7V-iqL5jcraATl
#vk1.a.g55hXxV7G857So0Wx4a2ZtvjLwvJA9_y7L6WqRhDmuOdngPCewdmVOtN-Fv-Q032grtWgm90qAytBYaBh-5pjo5LqR8xyjK5eBRfo5bjzAv0L_qSRsC3OhAhqqlEM0aX7P-W1XXrWu8ByxT2XfzKwIkOUjLQH6kkmxipNepSa0e5xpxgABnx6afsuyva8FwvGefOHH6bOA0TTXhweyFvYA
session:
  key: key_to_generate
admin:
  email: admin@admin.com
  password: admin
bot:
  token: group_token
  group_id: 1


